server:
  port: 8080
spring:
  application:
    name: cloud-grpc-client
  sleuth:
    sampler:
      probability: 1
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      host: 127.0.0.1
      port: 8500